# Generated by Django 6.1 on 2026-08-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_useranswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon',
        ),
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('SSC', 'SSC'), ('HSC', 'HSC')], default='SSC', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
