# Generated by Django 6.1 on 2026-08-17 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_subject_description_remove_subject_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz',
        ),
        migrations.AddField(
            model_name='question',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='লুপ সিরিয়াল নম্বর'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'এমসিকিউ (MCQ)'), ('solve', 'সলভ প্রশ্ন (Solving Question)')], default='mcq', max_length=10, verbose_name='প্রশ্নের ধরন'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='ব্যাখ্যা / সলভ'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200, verbose_name='কুইজের শিরোনাম/অধ্যায়'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.option'),
        ),
    ]
