# Generated by Django 6.1 on 2026-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_lesson_options_lesson_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['serial_number']},
        ),
        migrations.AddField(
            model_name='question',
            name='loop_serial',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='serial_number',
            field=models.PositiveIntegerField(default=1, verbose_name='ক্রমিক নম্বর'),
        ),
        migrations.AddField(
            model_name='question',
            name='solution_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
